MODULE FNVAR
 IMPLICIT NONE
 SAVE
 INTEGER :: lim, lim1, hm, n
 INTEGER :: loop = 0
 DOUBLE PRECISION :: mass
 DOUBLE PRECISION :: r,p,a,b
END MODULE FNVAR

MODULE VARSAVE
 IMPLICIT NONE
 SAVE
 DOUBLE PRECISION :: rsave = 1232.0d0 ! arbitrary !
 DOUBLE PRECISION, ALLOCATABLE :: Vrsave(:)
END MODULE VARSAVE

MODULE ROOT
 IMPLICIT NONE
 SAVE
 INTEGER :: count = 0
 DOUBLE PRECISION :: factvar(0:30)
 DOUBLE PRECISION, ALLOCATABLE :: z(:), E(:,:), WT(:)
END MODULE ROOT
